### ISSUE TITLE
Update documentation link to apache.github.io/incubator-horaedb-docs?

### ISSUE THREAD

**Issue by choznerol** [apache/incubator-horaedb-docs#111]
The documentation link in most places (e.g. the README) is eitehr https://ceresdb.github.io/docs or https://docs.ceresdb.io/, which are unavailable now, perhaps related to recent rename (e.g. #108).
It seems only https://apache.github.io/incubator-horaedb-docs works now. Not sure if you would want to setup a redirect or update existing links.

**Comment by tanruixiang** [comment]
Thank you very much for your attention. Our project just went to apache org today, so there may be a lot of links that need to be changed. Our expectation is to replace all the links with apache related ones.

**Comment by tanruixiang** [comment]
We should have most of the renaming taken care of in the next few days

**Comment by tanruixiang** [comment]
closed by https://github.com/apache/incubator-horaedb-docs/pull/112 Thank you for your attention.
